/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComplaintRouteImport } from './routes/complaint'
import { Route as FileComplaintRouteImport } from './routes/file-complaint'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyComplaintsRouteImport } from './routes/my-complaints'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as OfficerLoginRouteImport } from './routes/officer.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintRoute = ComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => rootRouteImport,
} as any)
const FileComplaintRoute = FileComplaintRouteImport.update({
  id: '/file-complaint',
  path: '/file-complaint',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyComplaintsRoute = MyComplaintsRouteImport.update({
  id: '/my-complaints',
  path: '/my-complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerLoginRoute = OfficerLoginRouteImport.update({
  id: '/officer/login',
  path: '/officer/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complaint': typeof ComplaintRoute
  '/file-complaint': typeof FileComplaintRoute
  '/login': typeof LoginRoute
  '/my-complaints': typeof MyComplaintsRoute
  '/register': typeof RegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/officer/login': typeof OfficerLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complaint': typeof ComplaintRoute
  '/file-complaint': typeof FileComplaintRoute
  '/login': typeof LoginRoute
  '/my-complaints': typeof MyComplaintsRoute
  '/register': typeof RegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/officer/login': typeof OfficerLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complaint': typeof ComplaintRoute
  '/file-complaint': typeof FileComplaintRoute
  '/login': typeof LoginRoute
  '/my-complaints': typeof MyComplaintsRoute
  '/register': typeof RegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/officer/login': typeof OfficerLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complaint'
    | '/file-complaint'
    | '/login'
    | '/my-complaints'
    | '/register'
    | '/admin/login'
    | '/officer/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complaint'
    | '/file-complaint'
    | '/login'
    | '/my-complaints'
    | '/register'
    | '/admin/login'
    | '/officer/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/complaint'
    | '/file-complaint'
    | '/login'
    | '/my-complaints'
    | '/register'
    | '/admin/login'
    | '/officer/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplaintRoute: typeof ComplaintRoute
  FileComplaintRoute: typeof FileComplaintRoute
  LoginRoute: typeof LoginRoute
  MyComplaintsRoute: typeof MyComplaintsRoute
  RegisterRoute: typeof RegisterRoute
  AdminLoginRoute: typeof AdminLoginRoute
  OfficerLoginRoute: typeof OfficerLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint': {
      id: '/complaint'
      path: '/complaint'
      fullPath: '/complaint'
      preLoaderRoute: typeof ComplaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-complaint': {
      id: '/file-complaint'
      path: '/file-complaint'
      fullPath: '/file-complaint'
      preLoaderRoute: typeof FileComplaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-complaints': {
      id: '/my-complaints'
      path: '/my-complaints'
      fullPath: '/my-complaints'
      preLoaderRoute: typeof MyComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/login': {
      id: '/officer/login'
      path: '/officer/login'
      fullPath: '/officer/login'
      preLoaderRoute: typeof OfficerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplaintRoute: ComplaintRoute,
  FileComplaintRoute: FileComplaintRoute,
  LoginRoute: LoginRoute,
  MyComplaintsRoute: MyComplaintsRoute,
  RegisterRoute: RegisterRoute,
  AdminLoginRoute: AdminLoginRoute,
  OfficerLoginRoute: OfficerLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
